name: Build using Docker Compose & Run unit tests on images

on: 
  push:
    branches:
      - main
      - add-new-workflows


jobs:


  build-and-test:
    runs-on: ubuntu-20.04
    env:

      PHONE: ${{ secrets.PHONE }}
      API_ID: ${{ secrets.API_ID }}
      API_HASH: ${{ secrets.API_HASH }}
      BOT_API_KEY: ${{ secrets.BOT_API_KEY }}

      PYTHONPATH: .
      LISTEN_ADDRESS: 0.0.0.0:8080
      POLL_CHANNELS_URL: http://telegram-poll-channels:8080/data
      ANSWERS_FILE: ./answers.yml
      USERS_DB_FILE: /listen_and_repeat_bot/listen_and_repeat_bot/bot_handler/data/users.db.json
      QUESTIONS_DB_FILE: /listen_and_repeat_bot/listen_and_repeat_bot/bot_handler/data/questions.db.json

    steps:
      - uses: actions/checkout@v3

      - run: |
          mkdir secrets
          echo "${{ secrets.LISTEN_AND_REPEAT_SESSION_ENCODED }}" | base64 --decode > ./secrets/listen_and_repeat.session
          echo -n "${{ secrets.CHANNEL_CONFIG }}" > ./secrets/config.yml

      - run: |
          docker compose up -d
          sleep 15

      - run: |
          docker compose logs
      
      - run: |
          poll_channel_restarts=$(docker inspect listen_and_repeat_bot-telegram-poll-channels-1 --format '{{ .RestartCount }}')
          bot_handler_restarts=$(docker inspect listen_and_repeat_bot-telegram-bot-handler-1 --format '{{ .RestartCount }}')

          echo "poll_channel_restarts=$poll_channel_restarts"
          echo "bot_handler_restarts=$bot_handler_restarts"
          exec 2>&1

          test $poll_channel_restarts -ne 0 && echo "problem A"
          test $bot_handler_restarts -ne 0 && echo "problem B"